kind: role
version: v7
metadata:
  name: aup-best-effort-drop
spec:
  options:
    create_db_user_mode: best_effort_drop
  allow:
    db_labels:
      "*": "*"
    db_names:
    - "*"
    db_roles:
    - creator

