tls-port 6379
port 0
aclfile /usr/local/etc/redis/users.acl
tls-ca-cert-file /usr/local/etc/redis/certs/redis.cas
tls-cert-file /usr/local/etc/redis/certs/redis.crt
tls-key-file /usr/local/etc/redis/certs/redis.key
tls-protocols "TLSv1.2 TLSv1.3"
